name: Keyboard checks
description: Keyboard related checks
body:
  - type: markdown
    attributes:
      value: |        
        > Note: this test requires you to use a keyboard and to visually identify interactive elements.

        <details>
        <summary>

        ## How to test

        </summary>

        The visual helper for this requirement highlights the elements in the target page that receive the input focus.
        1. Use your keyboard to move input focus through all the interactive elements in the page:
          - Use Tab and Shift+Tab to navigate between standalone controls.
          - Use the arrow keys to navigate between the focusable elements within a composite control.
        2. Record your results for each requirement:
          - If you find any failures, select Fail, then add them as failure instances.
          - Select Pass if all instances meet the requirement.
          - Review any auto-discovered failures to be sure they are valid.

        </details>
  - type: dropdown
    attributes:
      label: Keyboard navigation
      description: All interactive elements can be reached using the Tab and arrow keys.
      options:
        - Pass
        - Fail
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Keyboard traps
      description: There are no interactive elements that “trap” input focus and prevent navigating away.
      options:
        - Pass
        - Fail
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Focus indicator
      description: All interactive elements give a visible indication when they have input focus. 
      options:
        - Pass
        - Fail
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Tab order
      description: The tab order is consistent with the logical order that's communicated visually.
      options:
        - Pass
        - Fail
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Input focus
      description: Input focus does not move unexpectedly without the user initiating it. 
      options:
        - Pass
        - Fail
    validations:
      required: true
