name: General issue
description: File a general accessibility issue
body:
  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: "Describe access issue"
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Page url
      description: "Page URL that was tested"
      placeholder: "https://gov.uk"
    validations:
      required: true
  - type: input
    id: element-path
    attributes:
      label: Element path
      description: "Path to element on page"
      placeholder: ".input:first-child"
  - type: textarea
    id: html-snippet
    attributes:
      label: HTML Snippet
      description: "HTML code that shows the issue"
      render: html
